// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kademlia.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	kademlia.proto

It has these top-level messages:
	Request
	Response
	Contact
	Target
	Nodes
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Contact   *Contact `protobuf:"bytes,1,opt,name=contact" json:"contact,omitempty"`
	NetworkId string   `protobuf:"bytes,3,opt,name=networkId" json:"networkId,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *Request) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

type Response struct {
	Contact *Contact `protobuf:"bytes,1,opt,name=contact" json:"contact,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type Contact struct {
	Id      []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *Contact) Reset()                    { *m = Contact{} }
func (m *Contact) String() string            { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()               {}
func (*Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Contact) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contact) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Target struct {
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Target) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type Nodes struct {
	Contact []*Contact `protobuf:"bytes,1,rep,name=contact" json:"contact,omitempty"`
}

func (m *Nodes) Reset()                    { *m = Nodes{} }
func (m *Nodes) String() string            { return proto.CompactTextString(m) }
func (*Nodes) ProtoMessage()               {}
func (*Nodes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Nodes) GetContact() []*Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "pb.Request")
	proto.RegisterType((*Response)(nil), "pb.Response")
	proto.RegisterType((*Contact)(nil), "pb.Contact")
	proto.RegisterType((*Target)(nil), "pb.Target")
	proto.RegisterType((*Nodes)(nil), "pb.Nodes")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Kademlia service

type KademliaClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	FindNode(ctx context.Context, in *Target, opts ...grpc.CallOption) (*Nodes, error)
}

type kademliaClient struct {
	cc *grpc.ClientConn
}

func NewKademliaClient(cc *grpc.ClientConn) KademliaClient {
	return &kademliaClient{cc}
}

func (c *kademliaClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/pb.Kademlia/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kademliaClient) FindNode(ctx context.Context, in *Target, opts ...grpc.CallOption) (*Nodes, error) {
	out := new(Nodes)
	err := grpc.Invoke(ctx, "/pb.Kademlia/FindNode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Kademlia service

type KademliaServer interface {
	Ping(context.Context, *Request) (*Response, error)
	FindNode(context.Context, *Target) (*Nodes, error)
}

func RegisterKademliaServer(s *grpc.Server, srv KademliaServer) {
	s.RegisterService(&_Kademlia_serviceDesc, srv)
}

func _Kademlia_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Kademlia/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kademlia_FindNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Target)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KademliaServer).FindNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Kademlia/FindNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KademliaServer).FindNode(ctx, req.(*Target))
	}
	return interceptor(ctx, in, info, handler)
}

var _Kademlia_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Kademlia",
	HandlerType: (*KademliaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Kademlia_Ping_Handler,
		},
		{
			MethodName: "FindNode",
			Handler:    _Kademlia_FindNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kademlia.proto",
}

func init() { proto.RegisterFile("kademlia.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xd7, 0x4e, 0xd7, 0xf6, 0x6e, 0xec, 0xe1, 0x3e, 0x85, 0xe1, 0xc3, 0xc8, 0x10, 0xf6,
	0x54, 0x70, 0xfb, 0x09, 0x82, 0x20, 0xc2, 0x90, 0xb0, 0x3f, 0x90, 0xee, 0x5e, 0x46, 0x98, 0x26,
	0xb5, 0x89, 0xf8, 0xf7, 0xa5, 0x49, 0x8b, 0x88, 0x08, 0x7b, 0xcb, 0x3d, 0xe7, 0x24, 0x5f, 0xee,
	0x81, 0xe5, 0x45, 0x13, 0xbf, 0xbf, 0x19, 0x5d, 0xb7, 0x9d, 0x0b, 0x0e, 0xf3, 0xb6, 0x91, 0x07,
	0x28, 0x14, 0x7f, 0x7c, 0xb2, 0x0f, 0x78, 0x0f, 0xc5, 0xc9, 0xd9, 0xa0, 0x4f, 0x41, 0x64, 0xeb,
	0x6c, 0x3b, 0xdf, 0xcd, 0xeb, 0xb6, 0xa9, 0x1f, 0x93, 0xa4, 0x46, 0x0f, 0xef, 0xa0, 0xb2, 0x1c,
	0xbe, 0x5c, 0x77, 0x79, 0x26, 0x31, 0x5d, 0x67, 0xdb, 0x4a, 0xfd, 0x08, 0xf2, 0x01, 0x4a, 0xc5,
	0xbe, 0x75, 0xd6, 0xf3, 0x95, 0x0f, 0xca, 0x3d, 0x14, 0x83, 0x86, 0x4b, 0xc8, 0x0d, 0xc5, 0xf0,
	0x42, 0xe5, 0x86, 0x50, 0x40, 0xa1, 0x89, 0x3a, 0xf6, 0x5e, 0xe4, 0x91, 0x34, 0x8e, 0x52, 0xc0,
	0xec, 0xa8, 0xbb, 0x33, 0xff, 0xb9, 0x23, 0x6b, 0xb8, 0x3d, 0x38, 0x62, 0xff, 0x1b, 0x3f, 0xfd,
	0x0f, 0xbf, 0x3b, 0x42, 0xf9, 0x32, 0xf4, 0x82, 0x1b, 0xb8, 0x79, 0x35, 0xf6, 0x8c, 0x31, 0x39,
	0xf4, 0xb2, 0x5a, 0xa4, 0x21, 0x2d, 0x25, 0x27, 0xb8, 0x81, 0xf2, 0xc9, 0x58, 0xea, 0x21, 0x08,
	0xbd, 0x97, 0x3e, 0xb2, 0xaa, 0xfa, 0x73, 0x44, 0xcb, 0x49, 0x33, 0x8b, 0x15, 0xef, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x85, 0xb8, 0xf4, 0x7b, 0x74, 0x01, 0x00, 0x00,
}
